// Copyright 2019 MinnPost <tech@minnpost.com>
//
// This software may be used and distributed according to the terms of the
// GNU General Public License version 2 or any later version.

public class MailchimpErrorResponse {
    public String type { get; set; }
    public String title { get; set; }
    public Integer status { get; set; }
    public String detail { get; set; }
    public String instance { get; set; }
}
